### ISSUE TITLE
Rule editor needs to have arrows pointing from one rule to another

### ISSUE THREAD

**Issue by vamaraju** [vamaraju/shuffle-the-rules#2]

**Comment by theWhyteRabbit** [comment]
Currently an arrow will point from one (Event or Action) to another event or action.

Branching to multiple Events or Actions is currently not supported.  This issue needs to be updated when progress is made on issue 79.

**Comment by vamaraju** [comment]
Branching to multiple rules is now supported :) . You can do this by creating a new Event/Action, and specifying a Previous Rule that already has a branch. It's not perfect, but closing this issue for now.
