### ISSUE TITLE
Saving/Loading of Data - Serialization/Deserialization

### ISSUE THREAD

**Issue by theWhyteRabbit** [vamaraju/shuffle-the-rules#23]

**Comment by theWhyteRabbit** [comment]
Partial implementation.
Classes have been made to implement Serializable.

Requires testing and discussion to determine current progress. @vamaraju please comment.

**Comment by vamaraju** [comment]
Both the editor tab and table tab (table grid) can be saved to file :) . So for the most part, serialization is complete.

**Comment by theWhyteRabbit** [comment]
ok :)
