### ISSUE TITLE
FR: 3.2.1.1.3.6 User can specify whether or not the Cards in the Pile are face down or face up or a combination of both.

### ISSUE THREAD

**Issue by vamaraju** [vamaraju/shuffle-the-rules#29]

**Comment by theWhyteRabbit** [comment]
Functionality has been implemented in GameCreation mode (user can set this field in the Table Tab).
This requires testing.

Will it also be implemented in Gameplay mode?  I think this requirement is from the Gameplay Mode section of our SRS, but we didn't explicitly specify where the user would specify this in our SRS.

Marked as "question" and "help wanted" to get input from other members.
