### ISSUE TITLE
Editor tab is incomplete

### ISSUE THREAD

**Issue by vamaraju** [vamaraju/shuffle-the-rules#3]

**Comment by theWhyteRabbit** [comment]
@vamaraju please provide update

**Comment by theWhyteRabbit** [comment]
Editor Tab current functionality:
- add Events and Actions with custom name, description, and previous rule
- When a user adds an Event or Action, it automatically appears in the gameflow pane, with an arrow connecting it to the previous rule
- Can scroll vertically and horizontally in pane where Actions and Events appear.
- User can drag Events and Actions in gameflow pane

**Comment by theWhyteRabbit** [comment]
@vamaraju can this be closed? (ie. finished for now except for changes that may be needed after testing/and Gameplay implementation?)

**Comment by vamaraju** [comment]
Yes; editor tab is finished for now. Closing this.
