### ISSUE TITLE
FR: 3.2.1.2.3.1 User can specify number of each type and suit of Card(s).

### ISSUE THREAD

**Issue by vamaraju** [vamaraju/shuffle-the-rules#32]

**Comment by theWhyteRabbit** [comment]
implementation completed in GameCreation. needs testing

**Comment by theWhyteRabbit** [comment]
dependent on issue 17.

Added FR to files:
CardSettings
CardRestrictionsMenuView
CardRestrictionsMenuController

PlayingCard
Suit
Card (not sure if this is needed. indirectly relates to this requirement)

**Comment by theWhyteRabbit** [comment]
alerts have been added to inform user of correct and incorrect updates.

**Comment by theWhyteRabbit** [comment]
Additional field Deck Settings - Num Decks was added.
When a user changes the number in this field, it automatically populates all card restrictions for all Card values (ace to king).

When I was testing this, it looked like when a user changed the Num Decks field, it overrode any current customization (ie. if a user had 4 hearts for ace, when you changed num decks to 1, the user would then have 1 heart for ace).

@vamaraju can you please comment?

**Comment by vamaraju** [comment]
Yes, this I noticed this too. If the user wants to customize the Card Restrictions and have them saved, they should not edit the Number of Decks. This will be left as-is for now. The Number of Decks setting is there just to quickly increase the number of cards for all suits and values, and will overwrite the card restrictions upon being set.

**Comment by theWhyteRabbit** [comment]
Ok. Thank you.
