### ISSUE TITLE
FR: 3.2.1.4.3.1 User can create a new game.

### ISSUE THREAD

**Issue by vamaraju** [vamaraju/shuffle-the-rules#36]

**Comment by theWhyteRabbit** [comment]
functionality has been implemented. requires testing.

**Comment by theWhyteRabbit** [comment]
Functionality has been implemented.
Requires testing.

**Comment by theWhyteRabbit** [comment]
After preliminary testing, creating a new game does not reset the Table Grid.

**Comment by theWhyteRabbit** [comment]
I'll investigate this while looking into saving the TableGrid in the GameCreation instance.

**Comment by vamaraju** [comment]
Bug fixed: New Game now resets the TableGrid back to default (and updated GameCreation accordingly).

**Comment by theWhyteRabbit** [comment]
CardRestrictionsMenu does not update after New Game is pressed.
Investigating whether it's a view update issue or a model update issue.

**Comment by theWhyteRabbit** [comment]
Discovered an issue - instance of GameCreation is stored inside CardRestrictionsMenuController.  **I am going to replace this.**
Also, think we should explicitly reset our major model classes with a reset() method inside each.  This will avoid pointer issues.
@vamaraju

**Comment by theWhyteRabbit** [comment]
I'm currently editing GameCreation mode.

**Comment by theWhyteRabbit** [comment]
Fixed the CardRestrictionsMenu issue.
When values are changed, the view doesn't update. Will take note. Should be fixed, but very minor. Will create issue.  Num Decks field also needs to be reset.

Should also implement a reset method for each major model class. Will create issue.

Further testing will be done to confirm functionality and requirements.
