### ISSUE TITLE
When adding event or action, need to be able to specify pre/post event/action

### ISSUE THREAD

**Issue by vamaraju** [vamaraju/shuffle-the-rules#4]

**Comment by theWhyteRabbit** [comment]
Currently the user can specify a previous rule.

@vamaraju Are we still going to allow the user to specify a post action as well?
If not, can you please close this?

**Comment by vamaraju** [comment]
For now, no post action. It is implicit in the graph based on all the pre-rules. May add it in later if there is time; closing for now.
