### ISSUE TITLE
FR: 3.2.1.5.3.1 Player Objects can be set to active or inactive.

### ISSUE THREAD

**Issue by vamaraju** [vamaraju/shuffle-the-rules#41]

**Comment by theWhyteRabbit** [comment]
currently working on a GUI design/implementation on paper.  Will get feedback when rough sketch is complete.

**Comment by theWhyteRabbit** [comment]
Players will be set to be active when the user specifies number of players in the Table Tab in GameCreation mode.
Going to have a button/switch to toggle player inactive in Gameplay mode.
