### ISSUE TITLE
FR: 3.2.1.6.3.3 User can create a Game Flow Sequence by linking Game Rules.

### ISSUE THREAD

**Issue by vamaraju** [vamaraju/shuffle-the-rules#45]

**Comment by theWhyteRabbit** [comment]
Editor Tab interface allows users to link Events and Actions by specifying Previous Rule when creating an Event or Action.  Lines with directional arrows will automatically be drawn when a new Event or Action is created.

Requires testing.

Currently can only specify 1 previous rule.

Currently there is no cross interaction between Events and Actions and game objects created in the Table Tab.
