### ISSUE TITLE
FR: 3.2.1.3.7.1 Load Event settings.

### ISSUE THREAD

**Issue by vamaraju** [vamaraju/shuffle-the-rules#46]

**Comment by theWhyteRabbit** [comment]
Partial implementation.
When clicking on an Event that has already been created, its settings (type, name, description, previous rule) will be displayed.

Missing implementation: loading Event settings from file. @theWhyteRabbit check on this.

Currently there is no cross interaction between Events and Actions and game objects created in the Table Tab.
