### ISSUE TITLE
FR: 3.2.1.3.7.3 User can edit Event actions and rules.

### ISSUE THREAD

**Issue by vamaraju** [vamaraju/shuffle-the-rules#48]

**Comment by theWhyteRabbit** [comment]
Partial implementation.
User can edit the name and description for Events and Actions, as well as specify the previous Rule.

Currently there is no cross interaction between Events and Actions and game objects created in the Table Tab.

**Comment by theWhyteRabbit** [comment]
Cross interaction between Events and Actions has been implemented.
Requires testing.
