### ISSUE TITLE
FR: 3.2.1.8.3.5 User can hide the grid.

### ISSUE THREAD

**Issue by vamaraju** [vamaraju/shuffle-the-rules#53]

**Comment by theWhyteRabbit** [comment]
Functionality implemented.
Requires testing.

**Comment by theWhyteRabbit** [comment]
Functionality implemented.
Requires testing.

**Comment by vamaraju** [comment]
Implemented in GameCreation. Will not be implemented in Gameplay. Closing this issue.

**Comment by vamaraju** [comment]
Reopened for tracking purposes.
