### ISSUE TITLE
FR: 3.2.1.9.3.2 User can specify Player Turn order.

### ISSUE THREAD

**Issue by vamaraju** [vamaraju/shuffle-the-rules#55]

**Comment by theWhyteRabbit** [comment]
Currently missing. Assigning to myself.

**Comment by theWhyteRabbit** [comment]
Reassigning to @vamaraju after conversation.

**Comment by theWhyteRabbit** [comment]
current implementation:
User sets max and min number or players.  Each player has a Turn Number.  Currently can edit the name of the Player associated with the turn number.
