### ISSUE TITLE
FR: 3.2.2.1.3.1 User can view their Hand.

### ISSUE THREAD

**Issue by vamaraju** [vamaraju/shuffle-the-rules#57]

**Comment by theWhyteRabbit** [comment]
Preliminary implementation finished.
Requires further design (look into cells and selection) and testing (actually using with a hand in a game-like situation).

**Comment by theWhyteRabbit** [comment]
Important message:
Selecting and deselecting cards in the PileView requires the user to use control + click.
Message was added to GameplayView.

**Comment by vamaraju** [comment]
Working and implemented in Show Hand button in GameplayView.

**Comment by vamaraju** [comment]
Reopened for tracking purposes.
