### ISSUE TITLE
FR: 3.2.2.1.3.2 User can sort their Hand.

### ISSUE THREAD

**Issue by vamaraju** [vamaraju/shuffle-the-rules#58]

**Comment by theWhyteRabbit** [comment]
Currently working on this.
Looking into Callbacks and a popup window.
Have paper prototype for GUI (with plan on how to do single and nested sorts), as well as the Sorting implementation from our class UML (not sure if it will be followed exactly).

**Comment by theWhyteRabbit** [comment]
Currently have a pop up Dialog (SortDialog)

**Comment by vamaraju** [comment]
Working and implemented in SortDialog. Shows up correctly in GameplayView.

**Comment by vamaraju** [comment]
Reopened for tracking purposes.
