### ISSUE TITLE
FR: 3.2.2.2.3.1 User can select Card(s) from Hand to play.

### ISSUE THREAD

**Issue by vamaraju** [vamaraju/shuffle-the-rules#59]

**Comment by theWhyteRabbit** [comment]
Card selection implementation in progress.

**Comment by theWhyteRabbit** [comment]
Important message:
Selecting and deselecting cards in the PileView requires the user to use control + click.
Message was added to GameplayView.

This was an issue for a couple days because it looked like things were not working.

**Comment by theWhyteRabbit** [comment]
User can now select Cards.
Requires testing.
