### ISSUE TITLE
FR: 3.2.2.2.3.6 User can place Card(s) on a Pile.

### ISSUE THREAD

**Issue by vamaraju** [vamaraju/shuffle-the-rules#64]

**Comment by theWhyteRabbit** [comment]
currently working on a GUI design/implementation on paper.  Will get feedback when rough sketch is complete.

**Comment by vamaraju** [comment]
Working and implemented in PlaceCardAction.

**Comment by vamaraju** [comment]
Reopened for tracking purposes.
