### ISSUE TITLE
FR: 3.2.2.3.3.2 Player will be notified when their Turn ends.

### ISSUE THREAD

**Issue by vamaraju** [vamaraju/shuffle-the-rules#66]

**Comment by theWhyteRabbit** [comment]
Current plan is to have notification come up as a GameplayMessage in the GameplayMessageView.

**Comment by vamaraju** [comment]
Implemented and works in OnTurnEndEvent.

**Comment by vamaraju** [comment]
Reopened for tracking purposes.
