### ISSUE TITLE
FR: 3.2.2.3.3.2 Player’s Turn will be skipped if Player is inactive.

### ISSUE THREAD

**Issue by vamaraju** [vamaraju/shuffle-the-rules#67]

**Comment by theWhyteRabbit** [comment]
currently working on a GUI design/implementation on paper.  Will get feedback when rough sketch is complete.

**Comment by theWhyteRabbit** [comment]
Players will be set to be active when the user specifies number of players in the Table Tab in GameCreation mode.
Going to have a button/switch to toggle player inactive in Gameplay mode.
