### ISSUE TITLE
POTENTIAL BUG - Can't select multiple cards

### ISSUE THREAD

**Issue by theWhyteRabbit** [vamaraju/shuffle-the-rules#75]
user should be able to select multiple cards at once in their hand (yes/no)? @vamaraju 

Was trying to change the selection model.
Could go with original idea (of creating a class and handling selection).

**Comment by vamaraju** [comment]
if it's an easy fix, then yes to multuple cards, but not at all necessary. we can leave it with single card selection only for now

**Comment by theWhyteRabbit** [comment]
We can now select and deselect multiple. (Need to use control click.) Still requires testing.
Closing this issue. All further related comments will be made on issue 57.
