### ISSUE TITLE
Complete Table Grid Functionality in Gameplay Mode

### ISSUE THREAD

**Issue by theWhyteRabbit** [vamaraju/shuffle-the-rules#85]

**Comment by theWhyteRabbit** [comment]
For TableGrid to display Cards correctly, will need to create Card Objects and put Cards into Piles based on user's specifications.

**Comment by theWhyteRabbit** [comment]
Currently it seems like there is no way to access the TableGrid.
I don't think that the Piles added to the TableGrid in the TableTab are added to GameCreation mode.
This is an issue.
Could this also partially explain why "new game" doesn't work for Table Tab?

**Comment by theWhyteRabbit** [comment]
TableGrid is being set inside GameCreation and is accessible.

**Comment by theWhyteRabbit** [comment]
The issue is with using drawGrid().
Commented out work for now.  Will come back to work on this.

**Comment by vamaraju** [comment]
This issue is fixed now, as far as I know. TableGrid updates correctly in GameCreation, and drawGrid() will now work as expected, assuming there is a TableGrid set in the TableGridView (which there always should be, now). New Game also works now for Table Tab.

**Comment by vamaraju** [comment]
If you need to create a new TableGridView, you can pass it in a TableGrid (there is a constructor for it now), and it will refresh itself accordingly, and it will set GameCreation to use the passed-in TableGrid so they stay in-sync.
