### ISSUE TITLE
Unhandled Exceptions (NumberFormat and NullPointer) Thrown when Using Num Decks in Card Restrictions Menu

### ISSUE THREAD

**Issue by theWhyteRabbit** [vamaraju/shuffle-the-rules#86]
Special case (revealed from testing):
If you put a character into one of the suit count fields, then change the value in the Num Decks field, an exception will be thrown.  Values will still update correctly (as far as I can tell).

**Comment by theWhyteRabbit** [comment]
Not only a special case.  When changing the value of Num Decks and no Card has been selected,
throws java.lang.NumberFormatException and java.lang.NullPointerException.

**Comment by vamaraju** [comment]
Fixed and pushed :)

**Comment by theWhyteRabbit** [comment]
Reopening because of Number Formatting Exception

**Comment by vamaraju** [comment]
I can't seem to replicate this. How are you getting the NumberFormattingException?

**Comment by theWhyteRabbit** [comment]
It would happen when I entered a number into the Num Decks field.  (I think one of your changes fixed it.)
I just tried it now, and could not replicate.  Going to close this.
