### ISSUE TITLE
TableGrid Coordinate System - possibly not intuitive for users - rename X and Y to Col and Row?

### ISSUE THREAD

**Issue by theWhyteRabbit** [vamaraju/shuffle-the-rules#87]
TableGrid is zero indexed.  This may not be intuitive for users who are not used to this.  We may want to add a message to the interface to let users know that the grid is zero indexed.

I'm not sure if our coordinate system is intuitive.  I've seen it used before, but it wasn't what I originally expected (it's not like a matrix).

tldr; Having the initial Pile on screen is a good idea, but I think we could make it clearer for the user by renaming X and Y to Column and Row.  (This would also match the GridPane documentation.)
Could also provide a message on screen to let the user know how the coordinate system works (that it's zero indexed).

**Comment by vamaraju** [comment]
I think you're right; I'll change it to Col and Row. Will fix this later.
