### ISSUE TITLE
Why is TableGrid Transient?

### ISSUE THREAD

**Issue by theWhyteRabbit** [vamaraju/shuffle-the-rules#89]
@vamaraju please comment.

**Comment by vamaraju** [comment]
I made it transient because I have to save/load it manually in GameCreation anyways when I load a file (see loadTableGrid() in GameCreation). Technically, it does NOT need to be transient. But I kept it that way kind of as a reminder, I guess....

**Comment by vamaraju** [comment]
Nevermind, I removed the transience haha....was not necessary anymore! Closing the issue
