### ISSUE TITLE
Minor Bug - When GameCreation instance is reset, views need to update.

### ISSUE THREAD

**Issue by theWhyteRabbit** [vamaraju/shuffle-the-rules#90]
Card Restrictions Menu does not update automatically (suit counts and Num Decks).
This is a minor issue because the views do update once changed by the user (ie. switch Card).

Call an update on all views when GameCreation is reset.

**Comment by vamaraju** [comment]
Working on this now

**Comment by vamaraju** [comment]
There is a related issue: card restrictions (and other menus) don't load/update properly when loading from file. Working on this now as well.

**Comment by vamaraju** [comment]
This issue (and the issue in my comment) is fixed now, as far as I can tell. CardRestrictionMenu updates upon saving/loading from file
