### ISSUE TITLE
BUG (with fix) - Game Logic Contradiction with Pile Sizes and Number of Available Cards

### ISSUE THREAD

**Issue by theWhyteRabbit** [vamaraju/shuffle-the-rules#92]
Bug - java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 thrown when a user's pile size constraints and card restrictions contradict.

How to replicate - Leave intial deck.  Add another Pile - Min: 0, Max: 5, Starting: 2.

How to fix:  When we validate, we need to check the constraints for ALL PILES to see if they contradict the Card Restrictions specified by the user.  This is part of our requirement **FR: 3.2.1.10.3.1 Check for contradictions in the game’s settings and the game’s flow. #56**

**Comment by vamaraju** [comment]
I just pushed a validation for this that runs upon clicking the Validate Game button in the Application Menu Bar. For now, if you directly open the GameplayView window without validating, you will still get the exception. This will be fixed later; GameplayView will not be openable unless the game is validated first. But for now, the validation has been coded, and GameplayView will still show the exception. Easier for testing GameplayView this way.

Closing this issue for now.
